### ISSUE TITLE
Registry Review

### ISSUE THREAD

**Issue by ngokevin** [naugtur/aframe-point-component#1]
- [x] Add screenshot to README.
- [x] Add link to demo in README and GitHub repo description.
- [x] Bump and test to 0.5.0
- [x] Should we `setObject3D('mesh')` instead of `points`?

**Comment by naugtur** [comment]
0.5.0 didn't exist when I made my PR ;)

will do 1,2,3

As for 4, the whole point of this component is to use the point object so that the simplest possible rendering is used in Three.js

**Comment by ngokevin** [comment]
4. is just for naming and for consistency for other parts of code that might look for it. It's still a mesh right?

**Comment by naugtur** [comment]
4. I'm no expert, but the sole purpose of this component is to use the special primitive type of 3D object to render a point which should be significantly more lightweight to render and transform.

**Comment by ngokevin** [comment]
It's not about the purpose of the component. It's seems to be a mesh, so I would set it on the object3D as a mesh. `setObject3D('mesh', yourPointObject)`.

**Comment by naugtur** [comment]
Ok, I got confused. For some reason I thought the name is affecting something.

**Comment by naugtur** [comment]
all done
